Save bookmarked properties
robocopkaka/house-renting-app pull request #11
Opened 2020-05-26 20:11 UTC by lyndachiwetelu

#### What does this PR do?
 - Allows a tenant user to create bookmark, fetch all bookmarks and delete bookmark of properties

#### Description of Task to be completed?
- Create Bookmark
- Fetch all Bookmarks
- Delete Bookmark

#### How should this be manually tested?
- To create a bookmark, send a POST Request to ` /bookmarks ` with body
`{"propertyId": 1}`
- To fetch all bookmarks send a GET Request to `/bookmarks`
- To delete added bookmark send a DELETE Request to `/bookmarks` with body
`{"propertyId": 1}`

#### Any background context you want to provide?
N/A

#### What are the relevant pivotal tracker stories?(if applicable)
https://www.pivotaltracker.com/story/show/172163132

2020-05-30 08:54 UTC, robocopkaka commented on src/controllers/bookmarkController.ts
> +                return res.status(400).json({message: 'Property with Id not found'});
Could you use a 404 here

2020-05-30 08:55 UTC, robocopkaka commented on src/controllers/bookmarkController.ts
> +            console.log('ERROR', error);
Also, remove the console statement

2020-05-30 08:55 UTC, robocopkaka commented on src/middleware/authenticateTenant.ts
> +
Add new line here

2020-05-30 08:55 UTC, robocopkaka commented on src/middleware/validation/schemas/bookmarkSchema.ts
> +
Also here

2020-05-31 08:39 UTC, fire-cracker commented on src/controllers/bookmarkController.ts
> +                return bookmark.toJSON()
Great work. Although why not just return the data coming from the database, why map through just to convert to JSON?

2020-05-31 08:42 UTC, fire-cracker commented on src/controllers/bookmarkController.ts
> +            res.status(200).json(bookmarks)
What about a scenario where there are no bookmarks. It would be better to catch that instead of returning server error

2020-05-31 08:43 UTC, fire-cracker commented on src/controllers/bookmarkController.ts
> +            const removed = await Bookmark.destroy({
KIndly rename this to something more descriptive e.g removedProperty

2020-05-31 08:46 UTC, fire-cracker commented on src/controllers/bookmarkController.ts
> +                return res.status(500).json({message: 'Bookmark not removed'});
I don't think internal server error should be thrown if not removed. The status code should reflect why it's not removed. The most likely situation would be because the bookmark was not found, which would be 404.

2020-05-31 08:54 UTC, fire-cracker commented on src/routes/bookmarksRouter.ts
> +    authenticateTenant,
Authenticating users and authenticating admin seems redundant. It's either you are an ordinary user or an admin. If a route is only for admins, then we add authenticateAdmin, if the route is open to all registered user then we use authenticateUser

2020-05-31 08:57 UTC, fire-cracker commented on src/routes/propertiesRouter.ts
> +  authenticateLandlord,
Why authenticate the person is a user and then authenticate the person is a landlord. If the person is a landlord then the person automatically a user

2020-05-31 08:58 UTC, fire-cracker requested changes
Job well done

2020-06-03 14:14 UTC, lyndachiwetelu commented on src/controllers/bookmarkController.ts
> +                return res.status(400).json({message: 'Property with Id not found'});
Addressed in 181ccae99e5dd59a38419c17daed6db5f49c5766

2020-06-03 14:14 UTC, lyndachiwetelu commented on src/controllers/bookmarkController.ts
> +            console.log('ERROR', error);
fixed in 181ccae99e5dd59a38419c17daed6db5f49c5766

2020-06-03 14:15 UTC, lyndachiwetelu commented on src/middleware/authenticateTenant.ts
> +
done in 181ccae99e5dd59a38419c17daed6db5f49c5766

2020-06-03 14:15 UTC, lyndachiwetelu commented on src/middleware/validation/schemas/bookmarkSchema.ts
> +
done in 181ccae99e5dd59a38419c17daed6db5f49c5766

2020-06-03 14:21 UTC, lyndachiwetelu commented on src/controllers/bookmarkController.ts
> +                return bookmark.toJSON()
@fire-cracker In the bookmark.toJSON() implementation, in `models/Bookmark.ts` the property attribute's toJson() is called, and that removes unnecessary attributes like dates created and updated from the property object. The result is then the same as if you called the property routes themselves - those also use property.toJson() which formats the property object as mentioned above.

2020-06-03 14:27 UTC, lyndachiwetelu commented on src/controllers/bookmarkController.ts
> +            res.status(200).json(bookmarks)
@fire-cracker I'm sorry I don't quite get this, can you explain further?

2020-06-03 14:29 UTC, lyndachiwetelu commented on src/controllers/bookmarkController.ts
> +                return res.status(500).json({message: 'Bookmark not removed'});
fixed in eeb012e005cc47a28b6da680b88af0a89d56b7fe

2020-06-03 14:30 UTC, lyndachiwetelu commented on src/controllers/bookmarkController.ts
> +            const removed = await Bookmark.destroy({
done in eeb012e005cc47a28b6da680b88af0a89d56b7fe

2020-06-22 20:27 UTC, lyndachiwetelu commented on src/controllers/bookmarkController.ts
> +            res.status(200).json(bookmarks)
done in 76f1fd53413a573dd0651dc854ee0b1793a3ddd8

2020-06-22 23:47 UTC, merged