Setup authentication For landlord
robocopkaka/house-renting-app pull request #4
Opened 2020-03-20 22:53 UTC by pawnjester

#### What does this PR do?
This PR is to handle everything relating to landlord authentication (login/signup)
#### Description of Task to be completed?
- Setup Login for Landlord
- Setup Signup for Landlord
#### How should this be manually tested?
- Pull from this branch
- Include your env.
- To run tests, remember to migrate your database
#### Any background context you want to provide?
Nil
#### What are the relevant pivotal tracker stories?(if applicable)
https://www.pivotaltracker.com/story/show/171429203
https://www.pivotaltracker.com/story/show/171429202

2020-03-20 22:57 UTC, robocopkaka commented on .env
> +DB_USER=postgres
Can you ignore this file

2020-03-20 22:58 UTC, pawnjester commented on .env
> +DB_USER=postgres
I ignored it but it is still showing

2020-03-20 23:02 UTC, robocopkaka commented on .env
> +DB_USER=postgres
Can you do `git rm --cached`  and push a commit

2020-03-20 23:09 UTC, robocopkaka commented on controllers/userController.js
> +export default class User {
Think this should be `Landlord` and not `User`

2020-03-21 09:44 UTC, robocopkaka commented on models/user.js
> +  // User.associate = models => {
You can remove this if it's not necessary

2020-03-25 03:14 UTC, robocopkaka commented on controllers/landlordController.js
> +          newUser,
Could this be changed to `user`

2020-03-25 03:15 UTC, robocopkaka commented on controllers/landlordController.js
> +        message: `Welcome back ${userFound.name}`,
Not sure if there's a need for the welcome message here but guess it's a personal preference for me so opening this to discussion. cc: @Anie96

2020-03-25 03:17 UTC, robocopkaka commented on middleware/validation.js
> +    let { email, password, name, phoneNumber } = req.body;
#TODO might help to add a different validation for when a field is passed that isn't among this four. Can be done later

2020-03-25 03:18 UTC, robocopkaka commented on tests/landlord.js
> +    after(() => db.User.destroy({
Any reason for this since we're already undoing migrations  before tests are run?

2020-03-25 03:18 UTC, robocopkaka commented on tests/landlord.js
> +    after(() => db.User.destroy({
Same as above

2020-03-25 03:18 UTC, robocopkaka commented on tests/landlord.js
> +})
Add newline here

2020-03-25 03:21 UTC, robocopkaka commented
Can you update the README to show that we need to add `SECRET_KEY` to our `.env` files with a random value and also update the PR description with test objects for both endpoints to help when we pull down the branch to test

2020-04-03 22:09 UTC, robocopkaka approved these changes
Approved. Thanks Emmanuel

2020-04-04 11:20 UTC, fire-cracker commented on controllers/landlordController.js
> +        message: `Welcome back ${userFound.name}`,
I am okay with the welcome message.  It's not bad idea to let your backend handle message format.

2020-04-04 11:55 UTC, fire-cracker requested changes
Kindly squash commits

2020-04-04 11:55 UTC, fire-cracker commented on controllers/landlordController.js
> +        error: 'Error signing in'
It's great having an error message. I do think our 500 status message should be generic though. Such as "Server error"

2020-04-04 11:55 UTC, fire-cracker commented on middleware/validation.js
> +}
Validating for inputs is great. This can be abstracted to prevent repetition.

2020-04-04 11:55 UTC, fire-cracker commented on tests/landlord.js
> +            expect(res.body.user).to.not.have.property('password');
Line 21  to 25 can be summarised into "expect(res.body.user).to.be.an.instanceof(Object).that.includes.all.keys('email', 'name', 'phoneNumber', 'password');"

2020-04-04 21:17 UTC, merged