Update Landlord information
robocopkaka/house-renting-app pull request #7
Opened 2020-04-11 23:03 UTC by lyndachiwetelu

#### What does this PR do?
- Allows updating of Landlord information(name and phone number)

#### Description of Task to be completed?
Added a new endpoint to update the landlord name and number and added tests for it

#### How should this be manually tested?
Send a PATCH request to /landlord/{id} with request body like below:
`{
	"name": "Landlord A edited8",
	"phoneNumber": "12345678"
}`

#### Any background context you want to provide?
N/A

#### What are the relevant pivotal tracker stories?(if applicable)
https://www.pivotaltracker.com/story/show/171429393

2020-04-11 23:15 UTC, robocopkaka approved these changes

2020-04-12 06:57 UTC, fire-cracker commented on src/middleware/validation/schemas/userSchema.ts
> +  name: Joi.string().trim().min(3).max(150),
Nice work. You do not have to define the conditions of the name and phone number again. It has already been defined.

2020-04-12 12:09 UTC, pawnjester approved these changes

2020-04-12 15:45 UTC, fire-cracker requested changes

2020-04-12 15:45 UTC, fire-cracker commented on src/middleware/validation/schemas/userSchema.ts
> +  name: Joi.string().trim().min(3).max(150),
Nice work. You do not have to define the conditions of the name and phone number again. It has already been defined.

2020-04-12 15:45 UTC, fire-cracker commented on src/tests/users.ts
> +    describe('/:id', () => {
Kindly put a brief summary of what this describe block does for better readability

2020-04-12 15:45 UTC, fire-cracker commented on src/tests/users.ts
> +                phoneNumber: '0888888888'
This could be abstracted since it's being used multiple times. This can be done by creating a mock file

2020-04-12 15:45 UTC, fire-cracker commented on src/controllers/userController.ts
> +          phoneNumber: phoneNumber || userFound.phoneNumber,
I think If a user does not send data for an update then there is no need to stress the database. It feels kinda redundant to me. Database optimization is important hence the need to reduce stress if possible,

2020-04-13 13:13 UTC, lyndachiwetelu commented on src/middleware/validation/schemas/userSchema.ts
> +  name: Joi.string().trim().min(3).max(150),
This was done to override the required() step for these fields because it is not required for updates @fire-cracker

2020-04-13 13:17 UTC, lyndachiwetelu commented on src/tests/users.ts
> +                phoneNumber: '0888888888'
I moved it to `src/tests/mocks/landlord.ts`, i hope this is what you mean @fire-cracker

2020-04-13 13:17 UTC, lyndachiwetelu commented on src/controllers/userController.ts
> +          phoneNumber: phoneNumber || userFound.phoneNumber,
Makes sense, changed in latest commit

2020-04-13 15:09 UTC, fire-cracker approved these changes

2020-04-13 15:09 UTC, fire-cracker requested changes
Kindly squash your commits

2020-04-13 16:50 UTC, fire-cracker approved these changes

2020-04-13 21:14 UTC, merged